server:
  port: 8082

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 7MB
  datasource:
    url: jdbc:mysql://localhost:3306/auction-portal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

resilience4j:
  retry:
    instances:
      CurrencyToUser:
        max-retry-attempts: 2
        wait-duration : 2000
      CurrencyToBase:
        max-retry-attempts: 2
        wait-duration: 2000

